#!/bin/bash -e

babel=$RACKT_PATH/node_modules/.bin/babel
webpack=$RACKT_PATH/node_modules/.bin/webpack

# get user defined config if any or use rackt-cli one
. $RACKT_PATH/tasks/getFilePath
webpackConfig=`getFilePath webpack.build.js`



# Clean old build
rm -rf build/

# Generate bundle for NPM
BUILD="$webpack --devtool source-map --config $webpackConfig --output-path ./build --output-filename index.js"
mkdir -p build
eval $BUILD
#$babel -d build/lib ./lib


# Generate bundle for Bower
DIST="$webpack --devtool source-map --config $webpackConfig"
mkdir -p dist
eval $DIST
eval "MINIFY=1 $DIST"

# Copy package
cp README.md build/
node -p 'p=require("./package");p.scripts=p.devDependencies=undefined;p.main="./index.js";JSON.stringify(p,null,2)' > build/package.json
