#!/bin/bash

echo "Usage: rackt <command> [<args>]"
echo ""
echo "Available commands:"
echo "  init      Generates a new component"
echo "  build     Build the project"
echo "  dev       Start the dev server"
echo "  release   Publish a new release to npm"
echo "            Use --preview or -p to preview release"
echo "  test      Run the test suite"
echo "            Use --ci for single run"
echo "  pages     Deploy the examples to gh-pages"
echo "  help      Show this help"
