#!/bin/bash

# the pages task generates a new orphan gh-pages branch
# this branch will include all builded examples and a generic index.html
# branch is pushed to github to update `http://username.github.io/project-name`

# make sure working directory is clean
DIRTY=$(git status | grep modified -c)
let DIRTY+=$(git status | grep Untracked -c)

if [ $DIRTY -gt 0 ] && [ "$1" != "-f" ]; then
  echo "\033[0;31m"Refusing to operate on unclean working directory"\033[0m"
  echo Use \"git status\" to see which files have been modified
  exit 1
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" == "gh-pages" ]; then
  echo "Switch first to the branch you wish to create pages from"
  exit 1
fi

echo "▶ delete local branch gh-pages"
git branch -D gh-pages
echo "▶ create local orphan branch gh-pages"
git checkout --orphan gh-pages

# get user defined config if any or use rackt-cli one
. $RACKT_PATH/tasks/getFilePath
webpackConfig=`getFilePath webpack.config.js`

$RACKT_PATH/node_modules/.bin/webpack --config $webpackConfig

# exclude everything from git staging except examples
find -E . ! -regex '.*/(examples|node_modules|\.git).*' -exec git rm -r --cached {} \;
git add examples
echo "include: [__build__]" > _config.yml
git add _config.yml

# create basic homepage using rackt-cli babel-node
echo `$(dirname "$0")/../node_modules/.bin/babel-node $(dirname "$0")/getExamplesIndex.js` > index.html
git add index.html

echo "▶ commit & push"
git commit -m "updating gh-pages"
git push -f origin gh-pages

echo "▶ restore $BRANCH"
git add .
git commit -m 'dummy commit'
git checkout $BRANCH
