#!/bin/bash

if [ "$1" == "--preview" ] || [ "$1" == "-P" ] || [ "$1" == "-p" ]; then
  # Preview release
  $RACKT_PATH/node_modules/rf-release/node_modules/.bin/changelog -t preview -s
else
  # Release to npm
  $RACKT_PATH/tasks/build
  $RACKT_PATH/node_modules/.bin/release
fi
