#!/bin/bash

server=$RACKT_PATH/node_modules/.bin/webpack-dev-server

# get user defined config if any or use rackt-cli one
. $RACKT_PATH/tasks/getFilePath
webpackConfig=`getFilePath webpack.config.js`

$server --inline --config $webpackConfig --content-base examples/ "$@"
