#!/bin/bash

eslint=$RACKT_PATH/node_modules/.bin/eslint
karma=$RACKT_PATH/node_modules/.bin/karma


# get user defined config if any or use rackt-cli one
. $RACKT_PATH/tasks/getFilePath
esLintConfig=`getFilePath .eslintrc`

$eslint -c $esLintConfig lib examples && \n
NODE_ENV=test $karma start $RACKT_PATH/karma.conf.js \"$@\"
