#!/bin/sh

#TODO: Need to pull these from config, or similar
#grep -o '"name":.*".*"' package.json
COMPONENT_NAME=ReactFoo
COMPONENT_FILE=react-foo

mkdir -p dist

NODE_ENV=production node_modules/.bin/browserify lib/index.js \
  -t reactify \
  -t browserify-shim \
  -t envify \
  --detect-globals false \
  -s $COMPONENT_NAME > dist/$COMPONENT_FILE.js

node_modules/.bin/uglifyjs dist/$COMPONENT_FILE.js \
  --compress warnings=false > dist/$COMPONENT_FILE.min.js
